export enum ErrorEnum {
    USER_EXISTS = "400:Email already exist",
    ROOM_IS_USED = "400:Room is registrated",
    TOKEN_IS_REQUIRE = "400:Token is required",
    CTUET_EMAIL = "400:This email must have the extension 'ctuet.edu.vn'!",
    USER_UNCONFIRMED = "400:Confirmation your email before!",
    USER_IS_BLOCKED = "400:User is blocked",
    USER_INVALID = "400:User not found or blocked",
    NO_PERMISSION = "400:Access was denied",
    INVALID_DATE = "400:Date invalid",
    ROLE_NOT_FOUND = "400:Role not found",
    USER_NOT_FOUND = "400:User not found",
    INVALID_VERIFICATION_TOKEN = "400:Invalid token",
    RECORD_NOT_FOUND = "400:This record does not exist",
    RECORD_IS_EXISTED = "400:This record already exist",
    MISSION_EXECUTION_FAILED = "500:Task execution failed",
    INVALID_LOGIN = "400:Invalid login, please log in again",
    PASSWORD_VERIFICATION_FAILED = "400:Confirmation password does not match",
    REQUEST_INVALIDATED = "400:The current request has expired",
}
